# we need admin permissions
sudo: required 

# install a copy of docker into our running container
services:
  -docker

before_install:
  - docker build -t jsond3rul0/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jsond3rul0/docker-react npm run test

